# Generated by Django 5.0.6 on 2024-06-22 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurer', '0001_initial'),
        ('policies', '__first__'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('home_address', models.CharField(help_text='Agent home address', max_length=255)),
                ('bvn', models.CharField(help_text='Agent BVN', max_length=11)),
                ('bank_account', models.CharField(help_text='Agent Bank account', max_length=10)),
                ('affiliated_company', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='insurer.insurer')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='policies.policies')),
            ],
            options={
                'abstract': False,
            },
            bases=('user.customuser',),
        ),
    ]
