# Generated by Django 5.0.6 on 2024-10-08 14:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='first_name',
            field=models.CharField(default=django.utils.timezone.now, help_text='Agent first name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='last_name',
            field=models.CharField(blank=True, help_text='Agent middle name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='middle_name',
            field=models.CharField(default=django.utils.timezone.now, help_text='Agent middle name', max_length=50),
            preserve_default=False,
        ),
    ]
