# Generated by Django 5.0.6 on 2024-10-23 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('insurer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='affiliated_company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='insurer.insurer'),
        ),
    ]
