# Generated by Django 5.0.6 on 2024-12-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='merchant_code',
            field=models.CharField(default=1, help_text='Agent merchant code for merchant representation on superpool', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='tenant_id',
            field=models.UUIDField(default='9249517e-3db5-4e8c-8ffd-28839ea8d815', help_text='Agent tenant uuid merchant representation on superpool'),
        ),
    ]
