# Generated by Django 5.0.6 on 2024-06-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='bank_account',
            field=models.CharField(help_text='Agent Bank account', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='bvn',
            field=models.CharField(help_text='Agent BVN', max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='home_address',
            field=models.CharField(help_text='Agent home address', max_length=255, unique=True),
        ),
    ]
