# Generated by Django 5.0.6 on 2024-06-26 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_alter_agent_bank_account_alter_agent_bvn_and_more'),
        ('insurer', '0003_alter_insurer_business_registration_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='affiliated_company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='insurer.insurer'),
        ),
    ]
