# Generated by Django 5.0.6 on 2024-06-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_remove_agent_gampid'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='agent_gampID',
            field=models.CharField(blank=True, help_text='GAMP ID for users associated with GAMP', null=True),
        ),
    ]
