# Generated by Django 5.0.6 on 2024-06-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_alter_agent_affiliated_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_gampID',
            field=models.CharField(blank=True, help_text='GAMP ID for users associated with GAMP', null=True, unique=True),
        ),
    ]
