# Generated by Django 5.0.6 on 2024-06-28 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_alter_agent_agent_gampid'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='otp_created_at',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
