# Generated by Django 5.0.6 on 2024-07-04 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_agent_otp_agent_otp_created_at'),
        ('policies', '0002_remove_policies_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_policy', to='policies.policies'),
        ),
    ]
