# Generated by Django 5.0.6 on 2024-07-08 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_alter_agent_policy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'verbose_name': 'agent', 'verbose_name_plural': 'agents'},
        ),
    ]
