# Generated by Django 5.0.6 on 2024-07-08 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_alter_agent_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={},
        ),
    ]
