# Generated by Django 5.0.6 on 2024-07-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_alter_agent_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='unyte_unique_agent_id',
            field=models.CharField(default=2, max_length=70, unique=True),
            preserve_default=False,
        ),
    ]
