# Generated by Django 5.0.6 on 2024-07-10 01:57

import django.db.models.deletion
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0014_agent_unyte_unique_agent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', django_resized.forms.ResizedImageField(crop=None, default='default.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[400, 400], upload_to='profile_pic')),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agents.agent')),
            ],
        ),
    ]
