# Generated by Django 5.0.6 on 2024-07-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0016_alter_agentprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_gampID',
            field=models.CharField(blank=True, help_text='GAMP ID for users associated with GAMP', null=True),
        ),
    ]
