# Generated by Django 5.0.6 on 2024-08-15 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0017_alter_agent_agent_gampid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='policy',
        ),
    ]
