# Generated by Django 5.0.6 on 2024-07-04 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('policies', '0002_remove_policies_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='policies.policies'),
        ),
    ]
