# Generated by Django 5.0.6 on 2024-07-04 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policies',
            name='device',
        ),
    ]
