# Generated by Django 5.0.6 on 2024-07-08 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_alter_agent_policy'),
        ('policies', '0002_remove_policies_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agent')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.policies')),
            ],
            options={
                'unique_together': {('agent', 'policy')},
            },
        ),
    ]
