# Generated by Django 5.0.6 on 2024-07-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_agentpolicy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentpolicy',
            options={'verbose_name': 'agent policy', 'verbose_name_plural': 'agent policies'},
        ),
        migrations.AddField(
            model_name='agentpolicy',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
