# Generated by Django 5.0.6 on 2024-07-08 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0004_alter_agentpolicy_options_agentpolicy_is_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policies',
            name='sold',
        ),
    ]
