# Generated by Django 5.0.6 on 2024-07-08 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurer', '0011_insurer_policies'),
        ('policies', '0005_remove_policies_sold'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsurerPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sold', models.BooleanField(default=False)),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurer.insurer')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policies.policies')),
            ],
            options={
                'verbose_name': 'insurer policy',
                'verbose_name_plural': 'insurer policies',
                'unique_together': {('insurer', 'policy')},
            },
        ),
    ]
