# Generated by Django 5.0.6 on 2024-08-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0006_insurerpolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentpolicy',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='policies',
            name='policy_type',
            field=models.CharField(default='device', help_text='The class a policy falls under. For now, we only support Device Policies', max_length=50),
        ),
        migrations.AlterField(
            model_name='policies',
            name='amount',
            field=models.CharField(help_text='Amount policy should be sold at', max_length=200),
        ),
        migrations.AlterField(
            model_name='policies',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date policy was created'),
        ),
        migrations.AlterField(
            model_name='policies',
            name='name',
            field=models.CharField(help_text='The name of the policy', max_length=200),
        ),
        migrations.AlterField(
            model_name='policies',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Date at which the policy was updated'),
        ),
        migrations.AlterField(
            model_name='policies',
            name='valid_from',
            field=models.DateTimeField(help_text='Date at which policy is valid from'),
        ),
        migrations.AlterField(
            model_name='policies',
            name='valid_to',
            field=models.DateTimeField(help_text='Policy Expiration date'),
        ),
        migrations.DeleteModel(
            name='InsurerPolicy',
        ),
    ]
