# Generated by Django 5.0.6 on 2024-08-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0007_agentpolicy_quantity_policies_policy_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policies',
            name='name',
            field=models.CharField(help_text='The name of the policy', max_length=200, unique=True),
        ),
    ]
