# Generated by Django 5.0.6 on 2024-08-15 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurer', '0017_remove_insurer_policies'),
        ('policies', '0008_alter_policies_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='policies',
            name='insurer',
            field=models.ForeignKey(default=24, help_text='Insurer that create the policy', on_delete=django.db.models.deletion.CASCADE, to='insurer.insurer'),
            preserve_default=False,
        ),
    ]
