# Generated by Django 5.0.6 on 2024-08-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0010_rename_quantity_agentpolicy_quantity_bought_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentpolicy',
            name='quantity_sold',
            field=models.IntegerField(default=0),
        ),
    ]
