# Generated by Django 5.0.6 on 2024-12-09 03:25

import django.db.models.deletion
import django_resized.forms
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the business', max_length=255, verbose_name='Business Name')),
                ('short_code', models.CharField(help_text='Unique short code indentifier used internally to identify a merchant or distributore.g. UBA-X224, GTB-3X2, KON-001, SLOT-001, WEMA-2286, etc.', max_length=10, unique=True, verbose_name='Merchant Short code')),
                ('support_email', models.EmailField(blank=True, default='', help_text='The contact email address of the business, for support if any', max_length=254, verbose_name='Support Email')),
                ('is_active', models.BooleanField(default=False, help_text='Designates if the merchant is active')),
                ('verified', models.BooleanField(default=False, help_text='Designates if the merchant is verified')),
                ('tax_identification_number', models.CharField(blank=True, help_text='Unique tax identification number issued by federal or inland revenue service', max_length=40, null=True, unique=True, verbose_name='TIN')),
                ('registration_number', models.CharField(blank=True, help_text='Government-issued registration number with the CAC', max_length=40, null=True, unique=True, verbose_name='Registration Number')),
                ('address', models.TextField(blank=True, default='', help_text='The physical address of the business', verbose_name='Business Address')),
                ('kyc_verified', models.BooleanField(blank=True, default=False, help_text='Designates if the business has been verified by the platform', verbose_name='KYC Verified')),
                ('tenant_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the merchant in the system', unique=True, verbose_name='Tenant ID')),
                ('otp', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('otp_created_at', models.TimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', django_resized.forms.ResizedImageField(crop=None, default='profile_pic/default.png', force_format=None, keep_meta=True, quality=-1, scale=None, size=[400, 400], upload_to='profile_pic')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.merchant')),
            ],
        ),
    ]
