# Generated by Django 5.0.6 on 2024-10-24 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitedAgents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_email', models.EmailField(help_text='Agent email', max_length=254)),
                ('insurer', models.ForeignKey(help_text='Insurer who invited agent', on_delete=django.db.models.deletion.CASCADE, to='insurer.insurer')),
            ],
            options={
                'verbose_name': 'INVITED AGENT',
                'verbose_name_plural': 'INVITED AGENTS',
            },
        ),
    ]
