# Generated by Django 5.0.6 on 2024-06-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurer',
            name='agents',
        ),
        migrations.AddField(
            model_name='insurer',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
