# Generated by Django 5.0.6 on 2024-06-22 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurer',
            name='business_name',
            field=models.CharField(help_text='Business name of insurer', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='insurer',
            name='business_registration_number',
            field=models.CharField(help_text='Bank registration number of Tax ID of insurer', max_length=50, unique=True),
        ),
    ]
