# Generated by Django 5.0.6 on 2024-06-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurer', '0002_alter_insurer_business_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurer',
            name='business_registration_number',
            field=models.CharField(help_text='Business registration number of Tax ID of insurer', max_length=50, unique=True),
        ),
    ]
