# Generated by Django 5.0.6 on 2024-11-12 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurer', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurer',
            name='insurer_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
