# Generated by Django 5.0.6 on 2024-06-26 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurer', '0004_insurer_gampid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurer',
            name='gampID',
        ),
    ]
