# Generated by Django 5.0.6 on 2024-07-04 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurer', '0009_insurerprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InsurerProfile',
        ),
    ]
