# Generated by Django 5.0.6 on 2024-07-04 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurer', '0010_delete_insurerprofile'),
        ('policies', '0002_remove_policies_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurer',
            name='policies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurer_policy', to='policies.policies'),
        ),
    ]
