# Generated by Django 5.0.6 on 2024-07-09 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurer', '0012_insurer_unyte_unique_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurer',
            old_name='unyte_unique_id',
            new_name='unyte_unique_insurer_id',
        ),
    ]
