# Generated by Django 5.0.6 on 2024-08-15 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurer', '0016_alter_insurerprofile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurer',
            name='policies',
        ),
    ]
