# Generated by Django 5.0.6 on 2024-08-21 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GampArbitraryPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('policy_name', models.CharField(help_text='Name of policy', max_length=200)),
                ('policy_type', models.CharField(choices=[], default='', help_text='Types of available policies', max_length=20)),
                ('description', models.TextField(help_text='Description of a policy', max_length=250)),
                ('price', models.CharField(help_text='Price for the policy', max_length=30)),
                ('insurer', models.CharField(help_text='Insurer that created the policy', max_length=100)),
                ('flat_fee', models.CharField(choices=[], help_text='Flat fee for the policies created')),
            ],
        ),
        migrations.CreateModel(
            name='GampArbitraryUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('first_name', models.CharField(help_text='First name of gamp customer', max_length=70)),
                ('last_name', models.CharField(help_text='Last name of gamp customer', max_length=70)),
                ('phone_number', models.CharField(help_text='Phone number customer', max_length=70)),
                ('email', models.EmailField(help_text='Email of gamp customer', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='GampArbitraryDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.UUIDField(help_text='Device id')),
                ('device_type', models.CharField(choices=[('iPhone', 'iPhone'), ('Samsung', 'Samsung')], help_text='Type of device', max_length=100)),
                ('model', models.CharField(help_text='Model of device', max_length=100)),
                ('customer', models.ForeignKey(help_text='Customer who owns this device', on_delete=django.db.models.deletion.CASCADE, to='gamp_env.gamparbitraryuser')),
            ],
        ),
        migrations.CreateModel(
            name='GampArbitraryClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(help_text='Claims id')),
                ('description', models.TextField(help_text="Description text on what damage(s) occurred to user's device", max_length=250)),
                ('issue', models.CharField(choices=[('My phone fell into water', 'WATER'), ("My phone's screen got cracked", 'CRACKED SCREEN'), ("My phone's battery spoilt", "My phone's battery spoilt")], help_text='What issue occurred to the phone', max_length=100)),
                ('address', models.CharField(help_text="User's address", max_length=244)),
                ('technician_address', models.CharField(help_text='Address of technician who will work on the phone', max_length=244)),
                ('status', models.CharField(choices=[('APPROVED', 'APPROVED'), ('PENDING', 'PENDING'), ('DECLINED', 'DECLINED')], default='PENDING', help_text='Status of the claim filled', max_length=20)),
                ('device', models.ForeignKey(help_text='Device user is trying to claim policy for', on_delete=django.db.models.deletion.CASCADE, to='gamp_env.gamparbitrarydevice')),
                ('customer', models.ForeignKey(help_text='User initiating claim', on_delete=django.db.models.deletion.CASCADE, to='gamp_env.gamparbitraryuser')),
            ],
        ),
    ]
