# Generated by Django 5.0.6 on 2024-08-24 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamp_env', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamparbitraryclaim',
            old_name='uuid',
            new_name='claim_uuid',
        ),
        migrations.RenameField(
            model_name='gamparbitrarypolicy',
            old_name='uuid',
            new_name='policy_uuid',
        ),
        migrations.RemoveField(
            model_name='gamparbitrarypolicy',
            name='flat_fee',
        ),
        migrations.RemoveField(
            model_name='gamparbitrarypolicy',
            name='price',
        ),
        migrations.CreateModel(
            name='GampArbitraryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_uuid', models.UUIDField()),
                ('product_name', models.CharField(help_text='Type of the product', max_length=100)),
                ('premium', models.CharField(help_text='Price of the product', max_length=100)),
                ('flat_fee', models.BooleanField(default=True)),
                ('policy', models.ForeignKey(help_text='Policy that the product is attached to', on_delete=django.db.models.deletion.CASCADE, to='gamp_env.gamparbitrarypolicy')),
            ],
        ),
    ]
