# Generated by Django 5.0.6 on 2024-08-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamp_env', '0002_rename_uuid_gamparbitraryclaim_claim_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamparbitraryproduct',
            name='product_type',
            field=models.CharField(default=1, help_text='Types of available product', max_length=20),
            preserve_default=False,
        ),
    ]
