# Generated by Django 5.0.6 on 2024-08-24 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamp_env', '0003_gamparbitraryproduct_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamparbitraryproduct',
            name='product_type',
        ),
    ]
