# Generated by Django 5.0.6 on 2024-08-24 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamp_env', '0005_remove_gamparbitraryproduct_policy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamparbitrarypolicy',
            name='product_type',
        ),
        migrations.CreateModel(
            name='GampPolicyProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy', models.ForeignKey(help_text='Policy associated to a product', on_delete=django.db.models.deletion.CASCADE, to='gamp_env.gamparbitrarypolicy')),
                ('product', models.ForeignKey(help_text='Product(s) associated to a policy', on_delete=django.db.models.deletion.CASCADE, to='gamp_env.gamparbitraryproduct')),
            ],
        ),
    ]
