# Generated by Django 5.0.6 on 2024-08-25 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamp_env', '0006_remove_gamparbitrarypolicy_product_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('insurer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('flat_fee', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('broker_commission', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='gamp_env.product')),
            ],
        ),
    ]
