# Generated by Django 5.0.6 on 2024-08-27 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamp_env', '0008_alter_product_product_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GampPolicyProducts',
        ),
    ]
