# Generated by Django 5.0.6 on 2024-08-27 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamp_env', '0010_gamppolicyproducts'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bought_date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(help_text='Customer who bought the policy', on_delete=django.db.models.deletion.CASCADE, to='gamp_env.gamparbitraryuser')),
                ('product_bought', models.ForeignKey(help_text='Product bought by customer', on_delete=django.db.models.deletion.CASCADE, to='gamp_env.producttype')),
            ],
        ),
    ]
