# Generated by Django 5.0.6 on 2024-10-16 13:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'USER', 'verbose_name_plural': 'USERS'},
        ),
    ]
