# Generated by Django 5.0.6 on 2024-12-09 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='reference_id',
        ),
    ]
