# Generated by Django 5.0.6 on 2024-06-22 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gampID',
            field=models.EmailField(blank=True, help_text='GAMP ID for users associated with GAMP', max_length=254, null=True, unique=True),
        ),
    ]
